// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmlKOYEGRIDeUzbN0CpFbInXEV85O9-2U',
    appId: '1:447227872283:web:b30329d4d69126adf2a4be',
    messagingSenderId: '447227872283',
    projectId: 'yugen-213cf',
    authDomain: 'yugen-213cf.firebaseapp.com',
    databaseURL: 'https://yugen-213cf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yugen-213cf.appspot.com',
    measurementId: 'G-5DCJF3QWH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR64YPFpVg8awdvb11zWelbhx5XjDXwEA',
    appId: '1:447227872283:android:79aee854e9b9e13df2a4be',
    messagingSenderId: '447227872283',
    projectId: 'yugen-213cf',
    databaseURL: 'https://yugen-213cf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yugen-213cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBymSB0URnDGJr-an2bKEHUqXwYwqngwPQ',
    appId: '1:447227872283:ios:7d08842098602eb2f2a4be',
    messagingSenderId: '447227872283',
    projectId: 'yugen-213cf',
    databaseURL: 'https://yugen-213cf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yugen-213cf.appspot.com',
    androidClientId: '447227872283-c1hvmchhplifq51v88sidmtanrasb3ui.apps.googleusercontent.com',
    iosClientId: '447227872283-egqk3h52qobbcb2mrl68e42slmrsmv50.apps.googleusercontent.com',
    iosBundleId: 'com.app.yugen',
  );
}
